[package]
name = "proof-verifier"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "proof-verifier"
path = "src/main.rs"

[dependencies]
base64.workspace = true
blake3.workspace = true
ed25519-dalek.workspace = true
jsonschema.workspace = true
proof-remote = { path = "../proof-remote" }
serde.workspace = true
serde_json.workspace = true
serde_json_canonicalizer.workspace = true
thiserror.workspace = true
time.workspace = true

[lints]
workspace = true
